WEBHOOK_PASSPHRASE = "INSERT PASSPHRASE HERE!"

API_KEY = "INSERT KEY HERE"
API_SECRET = "INSERT KEY HERE"

REPORT = True
DISCORD_GROUP_ID = "INSERT GROUP ID HERE"
DISCORD_LINK = f"https://discord.com/api/v9/channels/{DISCORD_GROUP_ID}/messages"
DISCORD_HEADER = {"authorization": "INSERT AUTH KEY HERE"}

STOP_LIMIT_DIFFERENCE = 0.1
STOP_LOSS = 0